#!/bin/bash

echo -n "Are you sure (Y/N)?"

answered=

while [[ ! $answered ]]; do
    read -rn 1 -s answer
    if [[ $answer = [Yy] ]]; then
        answered="Yes"
    elif [[ $answer = [Nn] ]]; then
        answered="No"
    fi
done

printf "\n%s\n" $answered
